{% set version = "1.0.0" %}

package:
  name: python-debian
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/p/python-debian/python-debian-{{ version }}.tar.gz
    sha256: e19d8d31a7bb2d5939dffd1c21d27d4e49bbb683bb061c24420295ecedf4b2ad
  - url: https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
    sha256: edaef632cbb643e4e7a221717a6c441a4c1a7c918e6e4d56debc3d8739b233f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
    - setuptools-scm >=6.2
    - wheel
  run:
    - chardet
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - debian
    - debian_bundle
  commands:
    - pip check

about:
  home: https://salsa.debian.org/python-debian-team/python-debian
  license: GPL-2.0-or-later
  license_file: gpl-2.0.txt
  summary: Debian package related modules

extra:
  recipe-maintainers:
    - mbargull
    - bollwyvl
