{% set version = "0.1.37" %}
{% set sha256 = "ab04f535155810c46c8abf3f7d46364b67b034c49ff8690cdb510092eee56750" %}

package:
  name: python-debian
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-debian/python-debian-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - chardet
    - python
    - six

test:
  imports:
    - debian
    - debian_bundle

about:
  home: https://salsa.debian.org/python-debian-team/python-debian
  license: GPL-3.0-or-later
  license_file: gpl-3.0.txt
  summary: Debian package related modules
  doc_url: https://python-debian-team.pages.debian.net/python-debian/
  dev_url: https://salsa.debian.org/python-debian-team/python-debian

extra:
  recipe-maintainers:
    - mbargull
