{% set version = "1.0.1" %}

package:
  name: python-debian
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/p/python-debian/python-debian-{{ version }}.tar.gz
    sha256: 3ada9b83a3d671b58081782c0969cffa0102f6ce433fbbc7cf21275b8b5cc771

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
    - setuptools-scm >=6.2
    - wheel
  run:
    - charset-normalizer
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - debian
  commands:
    - pip check

about:
  home: https://salsa.debian.org/python-debian-team/python-debian
  license: GPL-2.0-or-later
  license_file: gpl-2.0.txt
  summary: Debian package related modules

extra:
  recipe-maintainers:
    - mbargull
    - bollwyvl
