# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.1.0"
  python_check_max: "3.14"

package:
  name: python-debian
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/python-debian/python_debian-${{ version }}.tar.gz
  sha256: afe3c7267d81c29c79ab44d803a0756d0796b0e41bb0a05c5cafcdd2b980d4e6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61
    - setuptools-scm >=6.2
    - wheel
  run:
    - charset-normalizer
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - debian
        - debian.arfile
        - debian.changelog
        - debian.copyright
        - debian.deb822
        - debian.debfile
        - debian.debian_support
        - debian.debtags
        - debian.substvars
        - debian.watch
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - mypy
        - ${{ python_min }}.*
    script:
      - mypy -p debian

about:
  license: GPL-2.0-or-later
  license_file: gpl-2.0.txt
  summary: Debian package related modules
  homepage: https://pypi.org/project/python-debian
  repository: https://salsa.debian.org/python-debian-team/python-debian

extra:
  recipe-maintainers:
    - mbargull
    - bollwyvl
